### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by SummerSeaSun** [gbeine/knx2mqtt#9]
Hi,

I would like to try this interesting project with the docker version:

`docker run -it --rm --name knx2mqtt -v ./knx2mqtt.conf:/etc/knx2mqtt.conf docker.io/gbeine/knx2mqtt`

**Knx2mqtt.conf.sample** got some comma missing at the end of line and multiple time defined parameter:

```
    "mqtt_port": "1883",
    "mqtt_port": "keepalive",

```

I've set: `    "mqtt_tls": "false", ` but got this error:
```

DEBUG:root:Starting MQTT
Traceback (most recent call last):
  File "/app/./knx2mqtt", line 388, in <module>
    main()
  File "/app/./knx2mqtt", line 381, in main
    mqtt_client = init_mqtt()
                  ^^^^^^^^^^^
  File "/app/./knx2mqtt", line 198, in init_mqtt
    mqtt_client.connect(daemon_args.mqtt_host, daemon_args.mqtt_port, daemon_args.mqtt_keepalive)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4612, in _create_socket
    sock = self._ssl_wrap_socket(sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4671, in _ssl_wrap_socket
    ssl_sock.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

```

Any advice to fix this error?
Thanks, BR

**Comment by SummerSeaSun** [comment]
Never mind the  "mqtt_tls": "false" is simply ignored, I've deleted the row and got it up.

**Comment by SummerSeaSun** [comment]
```
DEBUG:root:Starting MQTT
DEBUG:paho.mqtt.client:Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k30) client_id=b'knx2mqtt'
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:paho.mqtt.client:Received CONNACK (0, 0)
INFO:root:Subscribe: bus/knx/4/0/11
INFO:xknx.log:XKNX v3.1.1 starting tunneling connection to KNX bus.
DEBUG:paho.mqtt.client:Sending SUBSCRIBE (d0, m1) [(b'bus/knx/4/0/11', 0)]
DEBUG:xknx.log:Starting tunnel from  PCIP:0 to KNXIPINTERFACE:3671
DEBUG:xknx.log:Could not establish connection to KNX/IP interface. OSError: [Errno 99] Address not available
DEBUG:paho.mqtt.client:Received SUBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/xknx/io/tunnel.py", line 107, in connect
    await self.transport.connect()
  File "/usr/local/lib/python3.12/site-packages/xknx/io/transport/udp_transport.py", line 151, in connect
    (self.transport, _) = await loop.create_datagram_endpoint(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1422, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1406, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 99] Address not available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./knx2mqtt", line 388, in <module>
    main()
  File "/app/./knx2mqtt", line 384, in main
    start_knx()
  File "/app/./knx2mqtt", line 222, in start_knx
    asyncio.run(run())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/./knx2mqtt", line 219, in run
    await knx_tunnel.start()
  File "/usr/local/lib/python3.12/site-packages/xknx/xknx.py", line 129, in start
    await self.knxip_interface.start()
  File "/usr/local/lib/python3.12/site-packages/xknx/io/knxip_interface.py", line 73, in start
    await self._start()
  File "/usr/local/lib/python3.12/site-packages/xknx/io/knxip_interface.py", line 101, in _start
    await self._start_tunnelling_udp(
  File "/usr/local/lib/python3.12/site-packages/xknx/io/knxip_interface.py", line 382, in _start_tunnelling_udp
    await self._interface.connect()
  File "/usr/local/lib/python3.12/site-packages/xknx/io/tunnel.py", line 124, in connect
    raise CommunicationError(
xknx.exceptions.exception.CommunicationError: Tunnel connection could not be established

```

If I start home assistant it gets connected to knxipinterface, can you please help debug?

**Comment by SummerSeaSun** [comment]
Simply delete the  row `"knx_local_ip": "willtakeipwithoutthisline"`

**Comment by SummerSeaSun** [comment]
I've started a fork and made a pull request:

https://github.com/gbeine/knx2mqtt/pull/10

I'd like to publish the state of the connection on a new topic: "bus/knx/connection": online or offline.
Now I can see that the status can be retrieved from connection_lost function that seems to reside inside xknx.

Any advice to how to get that info (as it came from async and I'm a little new to these)?

```
knx2mqtt  | [10-23 10:17:41] p1 {_start_tunnelling_udp:364} DEBUG    - Starting tunnel from 172.24.0.2:0 to 10.7.208.158:3671
knx2mqtt  | [10-23 10:17:41] p1 {_easy_log      :3259} DEBUG    - Received SUBACK
knx2mqtt  | [10-23 10:17:41] p1 {send           :159} DEBUG    - Sending to 10.7.208.158:3671: <KNXIPFrame <KNXIPHeader HeaderLength="6" ProtocolVersion="16" KNXIPServiceType="CONNECT_REQUEST" TotalLength="26" /> body="<ConnectRequest control_endpoint="0.0.0.0:0/udp" data_endpoint="0.0.0.0:0/udp" cri="<ConnectRequestInformation connection_type="TUNNEL_CONNECTION" knx_layer="DATA_LINK_LAYER" />" />" />
knx2mqtt  | [10-23 10:17:42] p1 {start          :52} DEBUG    - Error: KNX bus did not respond in time (1.0 secs) to request of type 'Connect'
knx2mqtt  | [10-23 10:17:42] p1 {connect        :111} DEBUG    - Could not establish connection to KNX/IP interface. CommunicationError: ConnectRequest failed. Status code: None
knx2mqtt  | [10-23 10:17:42] p1 {connection_lost:57} DEBUG    - Closing UDP transport.
knx2mqtt  | Traceback (most recent call last):
knx2mqtt  |   File "/usr/local/lib/python3.12/site-packages/xknx/io/tunnel.py", line 109, in connect
knx2mqtt  |     await self._connect_request()
knx2mqtt  |   File "/usr/local/lib/python3.12/site-packages/xknx/io/tunnel.py", line 209, in _connect_request
knx2mqtt  |     raise CommunicationError(
knx2mqtt  | xknx.exceptions.exception.CommunicationError: ConnectRequest failed. Status code: None
knx2mqtt  | 
knx2mqtt  | The above exception was the direct cause of the following exception:
knx2mqtt  | 
knx2mqtt  | Traceback (most recent call last):
knx2mqtt  |   File "/app/./knx2mqtt", line 489, in <module>
knx2mqtt  |     main()
knx2mqtt  |   File "/app/./knx2mqtt", line 485, in main
knx2mqtt  |     start_knx()
knx2mqtt  |   File "/app/./knx2mqtt", line 259, in start_knx
knx2mqtt  |     asyncio.run(run())
knx2mqtt  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
knx2mqtt  |     return runner.run(main)
knx2mqtt  |            ^^^^^^^^^^^^^^^^
knx2mqtt  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
knx2mqtt  |     return self._loop.run_until_complete(task)
knx2mqtt  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
knx2mqtt  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
knx2mqtt  |     return future.result()
knx2mqtt  |            ^^^^^^^^^^^^^^^
knx2mqtt  |   File "/app/./knx2mqtt", line 256, in run
knx2mqtt  |     await knx_tunnel.start()
knx2mqtt  |   File "/usr/local/lib/python3.12/site-packages/xknx/xknx.py", line 129, in start
knx2mqtt  |     await self.knxip_interface.start()
knx2mqtt  |   File "/usr/local/lib/python3.12/site-packages/xknx/io/knxip_interface.py", line 73, in start
knx2mqtt  |     await self._start()
knx2mqtt  |   File "/usr/local/lib/python3.12/site-packages/xknx/io/knxip_interface.py", line 101, in _start
knx2mqtt  |     await self._start_tunnelling_udp(
knx2mqtt  |   File "/usr/local/lib/python3.12/site-packages/xknx/io/knxip_interface.py", line 382, in _start_tunnelling_udp
knx2mqtt  |     await self._interface.connect()
knx2mqtt  |   File "/usr/local/lib/python3.12/site-packages/xknx/io/tunnel.py", line 124, in connect
knx2mqtt  |     raise CommunicationError(
knx2mqtt  | xknx.exceptions.exception.CommunicationError: Tunnel connection could not be established

```
Obviously now the ethernet cable is plugged out from ip interface to test this condition.
